name:                augmented-ai-translation
version:             0.1.0.0
github:              "mtamc/augmented-ai-translation"
license:             MIT
author:              "mtamc"
maintainer:          "mtamc"
copyright:           "2023 mtamc"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <url_here>

dependencies:
- base-noprelude
- relude
- base-unicode-symbols
- text
- containers
- lens
- generic-lens
- mtl
- safe-exceptions
- aeson
- process
- http-conduit
- http-types
- extra
- http-client
- time
- megaparsec
- HTTP
- filepath
- os-string

language: GHC2021

default-extensions:
- OverloadedStrings
- OverloadedLabels
- UnicodeSyntax
- NoFieldSelectors
- LambdaCase
- DuplicateRecordFields
- ViewPatterns
- BlockArguments
- DataKinds
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src

executables:
  augmented-ai-translation-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=.hie
    dependencies:
    - augmented-ai-translation
